### PR TITLE
Update thumbnail cache if a user changes their avatar

### PR DESCRIPTION
**Pull request by Fryboy**

### CODE REVIEW

**Comment by numegil** [comment]
I'm still not sure I understand the root of the problem. Are these the only sizes that matter? Do we need also create thumbnails for other sizes, or do those happen automatically?

**Comment by Fryboy** [comment]
Hrm, interesting.
I didn't test it on the other sizes.
BRB!

**Comment by Fryboy** [comment]
The little Forum thumbnails updated without this change

**Comment by Fryboy** [comment]
As did the mouse-over ones, so it appears it's just the large ones that are cached?

**Pull request merged**
